
apiVersion: v1
kind: Service
metadata:
  name: demoappwar
  labels:
    app: demoappwar
spec:
  ports:
    - port: 9080
  selector:
    app: demoappwar
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demoappwar
  name: demoappwar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoappwar
    spec:
      containers:
      - image: mycluster.icp:8500/default/demoappwar:latest
        name: demoappwar
        ports:
        - containerPort: 9080
          protocol: TCP
